-- JC Handyman CRM V18 Phase 1 Field Service
-- Run in Supabase SQL Editor.

create table if not exists public.field_checkins (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  job_id bigint,
  checkin_type text,
  location_note text,
  latitude numeric,
  longitude numeric,
  notes text
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  job_id bigint,
  title text,
  appointment_type text,
  appointment_date date,
  appointment_time time,
  status text,
  notes text
);

create table if not exists public.job_photos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  job_id bigint,
  photo_type text,
  photo_url text,
  notes text
);

create table if not exists public.signatures (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  job_id bigint,
  signature_type text,
  title text,
  signature_url text,
  notes text
);

alter table public.field_checkins enable row level security;
alter table public.appointments enable row level security;
alter table public.job_photos enable row level security;
alter table public.signatures enable row level security;

drop policy if exists "Allow public select field_checkins" on public.field_checkins;
drop policy if exists "Allow public insert field_checkins" on public.field_checkins;
drop policy if exists "Allow public select appointments" on public.appointments;
drop policy if exists "Allow public insert appointments" on public.appointments;
drop policy if exists "Allow public select job_photos" on public.job_photos;
drop policy if exists "Allow public insert job_photos" on public.job_photos;
drop policy if exists "Allow public select signatures" on public.signatures;
drop policy if exists "Allow public insert signatures" on public.signatures;

create policy "Allow public select field_checkins" on public.field_checkins for select using (true);
create policy "Allow public insert field_checkins" on public.field_checkins for insert with check (true);
create policy "Allow public select appointments" on public.appointments for select using (true);
create policy "Allow public insert appointments" on public.appointments for insert with check (true);
create policy "Allow public select job_photos" on public.job_photos for select using (true);
create policy "Allow public insert job_photos" on public.job_photos for insert with check (true);
create policy "Allow public select signatures" on public.signatures for select using (true);
create policy "Allow public insert signatures" on public.signatures for insert with check (true);

insert into public.crm_upgrades (version, upgrade_name, notes, status)
values ('V18 Phase 1', 'Field Service Tools', 'Added calendar, GPS check-in, before/after photos, signatures, estimate generator, and invoice generator.', 'Installed');
