-- JC Handyman Cloud CRM V15 Upgrade System
-- Run this in Supabase SQL Editor.

create table if not exists public.crm_upgrades (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  version text,
  upgrade_name text,
  notes text,
  status text
);

alter table public.crm_upgrades enable row level security;

drop policy if exists "Allow public select crm_upgrades" on public.crm_upgrades;
drop policy if exists "Allow public insert crm_upgrades" on public.crm_upgrades;

create policy "Allow public select crm_upgrades"
on public.crm_upgrades
for select
using (true);

create policy "Allow public insert crm_upgrades"
on public.crm_upgrades
for insert
with check (true);

insert into public.crm_upgrades (version, upgrade_name, notes, status)
values (
  'V15',
  'Upgrade System',
  'Added upgrade tracking table and upgrade checklist workflow.',
  'Installed'
);
