-- JC Handyman Cloud CRM V14 Smart Operations

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  quantity numeric,
  low_stock numeric,
  cost numeric,
  supplier text,
  notes text
);

create table if not exists public.work_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  job_id bigint,
  title text,
  status text,
  scope text,
  due_date date
);

alter table public.materials enable row level security;
alter table public.work_orders enable row level security;

drop policy if exists "Allow public select materials" on public.materials;
drop policy if exists "Allow public insert materials" on public.materials;
drop policy if exists "Allow public select work_orders" on public.work_orders;
drop policy if exists "Allow public insert work_orders" on public.work_orders;

create policy "Allow public select materials" on public.materials for select using (true);
create policy "Allow public insert materials" on public.materials for insert with check (true);
create policy "Allow public select work_orders" on public.work_orders for select using (true);
create policy "Allow public insert work_orders" on public.work_orders for insert with check (true);
