-- JC Handyman Cloud CRM V13 Enterprise

create table if not exists public.client_portal_records (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  status text,
  notes text
);

create table if not exists public.service_plans (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  plan_name text,
  start_date date,
  renewal_date date,
  notes text
);

create table if not exists public.managed_properties (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_id bigint,
  address text,
  property_type text,
  notes text
);

alter table public.client_portal_records enable row level security;
alter table public.service_plans enable row level security;
alter table public.managed_properties enable row level security;

drop policy if exists "Allow public select client_portal_records" on public.client_portal_records;
drop policy if exists "Allow public insert client_portal_records" on public.client_portal_records;
drop policy if exists "Allow public select service_plans" on public.service_plans;
drop policy if exists "Allow public insert service_plans" on public.service_plans;
drop policy if exists "Allow public select managed_properties" on public.managed_properties;
drop policy if exists "Allow public insert managed_properties" on public.managed_properties;

create policy "Allow public select client_portal_records" on public.client_portal_records for select using (true);
create policy "Allow public insert client_portal_records" on public.client_portal_records for insert with check (true);
create policy "Allow public select service_plans" on public.service_plans for select using (true);
create policy "Allow public insert service_plans" on public.service_plans for insert with check (true);
create policy "Allow public select managed_properties" on public.managed_properties for select using (true);
create policy "Allow public insert managed_properties" on public.managed_properties for insert with check (true);
