alter table public.customers enable row level security;
alter table public.jobs enable row level security;
alter table public.website_leads enable row level security;
drop policy if exists "Allow public select customers" on public.customers;
drop policy if exists "Allow public insert customers" on public.customers;
drop policy if exists "Allow public select jobs" on public.jobs;
drop policy if exists "Allow public insert jobs" on public.jobs;
drop policy if exists "Allow public select leads" on public.website_leads;
drop policy if exists "Allow public insert leads" on public.website_leads;
create policy "Allow public select customers" on public.customers for select using (true);
create policy "Allow public insert customers" on public.customers for insert with check (true);
create policy "Allow public select jobs" on public.jobs for select using (true);
create policy "Allow public insert jobs" on public.jobs for insert with check (true);
create policy "Allow public select leads" on public.website_leads for select using (true);
create policy "Allow public insert leads" on public.website_leads for insert with check (true);
